//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 16.0.02
//      Generation date : niedziela, 6 maja 2018
//      Generated by    : DominikaRaczak
//      JADE Schema     : JadeProject
//      Exposure Name   : JadeProject
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace JadeProject
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(CustomersById))]
	public partial class CustomersByIdKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _id = MetadataCache<CustomersByIdMetadata>.GetData(null).IdKey;

		public CustomersByIdKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_id})
		{
		}

		public CustomersByIdKey(Int32 id) :
				this()
		{
			this.Id = id;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("id", 0, typeof(Int32), Length = 4, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public Int32 Id
		{
			get
			{
				return ((Int32)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Customer))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomersByIdKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(CustomersByIdMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("CustomersById", "RootSchema.JadeProject", ClassNamespace = "JadeProject", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "CustomersById", typeof(MemberKeyDictionary<CustomersByIdKey, Customer>), MembershipType=typeof(Customer), Keys="id")]
	public partial class CustomersById : MemberKeyDictionary<CustomersByIdKey, Customer>
	{

		private static CustomersByIdMetadata _metaModel;

		partial void Initialize();


		static CustomersById()
		{
			_metaModel = MetadataCache<CustomersByIdMetadata>.GetData(null);
		}

		private CustomersById() : 
				this(JadeSoftware.Joob.ClassPersistence.Transient)
		{
		}

		public CustomersById(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(CustomersById), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected CustomersById(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual Customer this[Int32 id]
		{
			get
			{
				CustomersByIdKey _key_ = new CustomersByIdKey(id);
				 return base[_key_];
			}
			set
			{
				CustomersByIdKey _key_ = new CustomersByIdKey(id);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(Int32 id, out Customer value)
		{
			CustomersByIdKey _key_ = new CustomersByIdKey(id);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(Int32 id, JadeSoftware.Joob.SearchStrategy strategy, out Customer value)
		{
			CustomersByIdKey _key_ = new CustomersByIdKey(id);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<CustomersByIdKey, Customer> StartingAtKey(Int32 id)
		{
			CustomersByIdKey _key_ = new CustomersByIdKey(id);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<CustomersByIdKey, Customer> StartingAtKey(Int32 id, JadeSoftware.Joob.SearchStrategy strategy)
		{
			CustomersByIdKey _key_ = new CustomersByIdKey(id);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void Remove(Int32 id)
		{
			CustomersByIdKey _key_ = new CustomersByIdKey(id);
			base.Remove(_key_);
		}

		public virtual void Remove(Int32 id, Customer member)
		{
			CustomersByIdKey _key_ = new CustomersByIdKey(id);
			base.Remove(_key_, member);
		}

		public virtual bool ContainsKey(Int32 id)
		{
			CustomersByIdKey _key_ = new CustomersByIdKey(id);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Customer))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomersByIdKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(CustomersByIdMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("CustomersById", "RootSchema.JadeProject", ClassNamespace="JadeProject")]
	public abstract partial class CustomersById<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : Customer
	{

		private static CustomersByIdMetadata _metaModel;

		partial void Initialize();


		static CustomersById()
		{
			_metaModel = MetadataCache<CustomersByIdMetadata>.GetData(null);
		}

		protected CustomersById(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class CustomersByIdMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata IdKey;

		private CustomersByIdMetadata()
		{
		}

		public CustomersByIdMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(CustomersById), "CustomersById", "RootSchema.JadeProject", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.IdKey = metaClass.CheckMemberKey(typeof(CustomersById), typeof(Customer), "id", typeof(Int32), JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
