//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 16.0.02
//      Generation date : niedziela, 6 maja 2018
//      Generated by    : DominikaRaczak
//      JADE Schema     : JadeProject
//      Exposure Name   : JadeProject
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace JadeProject
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;

	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(CustomerMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("Customer", "RootSchema.JadeProject", ClassNamespace="JadeProject")]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.Class, "Customer", typeof(Person))]
	public partial class Customer : Person
	{
		private static CustomerMetadata _metaModel;
		partial void _initialize();
		static Customer()
		{
			_metaModel = MetadataCache<CustomerMetadata>.GetData(null);
		}
		public Customer() :
			this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}
		public Customer(JadeSoftware.Joob.ClassPersistence lifetime) :
			base(lifetime, typeof(Customer), _metaModel.metaClass)
		{
			this._initialize();
		}
		protected Customer(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
			base(lifetime, type, metaClass)
		{
			this._initialize();
		}
	
#region Jade Properties

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("login", typeof(String), Length=30, DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String Login
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.login);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.login, value);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("password", typeof(String), Length=30, DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String Password
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.password);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.password, value);
			}
		}
	#endregion
	
#region Jade Methods

		[JadeSoftware.Joob.Client.JoobMethodAttribute("canHaveDiscount")]
		public new Boolean CanHaveDiscount()
		{
			using (JadeParam retnParam = new JadeParamBoolean(Usage.Output))
			{
				this.SendMessage(_metaModel.canHaveDiscount, retnParam);
				return (retnParam as JadeParamBoolean).Value;
			}

		}

		[JadeSoftware.Joob.Client.JoobMethodAttribute("setOnCreate")]
		public void SetOnCreate(String pName, String pSurname, Int32 pAge, String pLogin, String pPassword)
		{
			using (JadeParam jadeParam1 = new JadeParamString(pName),
							jadeParam2 = new JadeParamString(pSurname),
							jadeParam3 = new JadeParamInteger(pAge),
							jadeParam4 = new JadeParamString(pLogin),
							jadeParam5 = new JadeParamString(pPassword))
			{
				this.SendMessage(_metaModel.setOnCreate, null, jadeParam1, jadeParam2, jadeParam3, jadeParam4, jadeParam5);
				return;
			}

		}
	#endregion
	}

	public partial class CustomerMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;
		internal JadeSoftware.Joob.MethodMetadata canHaveDiscount;
		internal JadeSoftware.Joob.PropertyMetadata login;
		internal JadeSoftware.Joob.PropertyMetadata password;
		internal JadeSoftware.Joob.MethodMetadata setOnCreate;

		private CustomerMetadata()
		{
		}
		partial void InitializeDynamicProperties(JadeSoftware.Joob.Client.IJoobConnection connection);

		public CustomerMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(Customer), "Customer", "RootSchema.JadeProject");
			this.InitializeProperties(connection);
			this.InitializeDynamicProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.IJoobConnection connection)
		{
			canHaveDiscount = metaClass.CheckMethod(metaClass,"canHaveDiscount");
			login = metaClass.CheckProperty("login", typeof(String), 30);
			password = metaClass.CheckProperty("password", typeof(String), 30);
			setOnCreate = metaClass.CheckMethod(metaClass,"setOnCreate");
		}
	}
}
