//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 16.0.02
//      Generation date : niedziela, 6 maja 2018
//      Generated by    : DominikaRaczak
//      JADE Schema     : JadeProject
//      Exposure Name   : JadeProject
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace JadeProject
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(EmployeesById))]
	public partial class EmployeesByIdKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _id = MetadataCache<EmployeesByIdMetadata>.GetData(null).IdKey;

		public EmployeesByIdKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_id})
		{
		}

		public EmployeesByIdKey(Int32 id) :
				this()
		{
			this.Id = id;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("id", 0, typeof(Int32), Length = 4, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public Int32 Id
		{
			get
			{
				return ((Int32)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Employee))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(EmployeesByIdKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(EmployeesByIdMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("EmployeesById", "RootSchema.JadeProject", ClassNamespace = "JadeProject", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "EmployeesById", typeof(MemberKeyDictionary<EmployeesByIdKey, Employee>), MembershipType=typeof(Employee), Keys="id")]
	public partial class EmployeesById : MemberKeyDictionary<EmployeesByIdKey, Employee>
	{

		private static EmployeesByIdMetadata _metaModel;

		partial void Initialize();


		static EmployeesById()
		{
			_metaModel = MetadataCache<EmployeesByIdMetadata>.GetData(null);
		}

		private EmployeesById() : 
				this(JadeSoftware.Joob.ClassPersistence.Transient)
		{
		}

		public EmployeesById(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(EmployeesById), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected EmployeesById(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual Employee this[Int32 id]
		{
			get
			{
				EmployeesByIdKey _key_ = new EmployeesByIdKey(id);
				 return base[_key_];
			}
			set
			{
				EmployeesByIdKey _key_ = new EmployeesByIdKey(id);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(Int32 id, out Employee value)
		{
			EmployeesByIdKey _key_ = new EmployeesByIdKey(id);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(Int32 id, JadeSoftware.Joob.SearchStrategy strategy, out Employee value)
		{
			EmployeesByIdKey _key_ = new EmployeesByIdKey(id);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<EmployeesByIdKey, Employee> StartingAtKey(Int32 id)
		{
			EmployeesByIdKey _key_ = new EmployeesByIdKey(id);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<EmployeesByIdKey, Employee> StartingAtKey(Int32 id, JadeSoftware.Joob.SearchStrategy strategy)
		{
			EmployeesByIdKey _key_ = new EmployeesByIdKey(id);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void Remove(Int32 id)
		{
			EmployeesByIdKey _key_ = new EmployeesByIdKey(id);
			base.Remove(_key_);
		}

		public virtual void Remove(Int32 id, Employee member)
		{
			EmployeesByIdKey _key_ = new EmployeesByIdKey(id);
			base.Remove(_key_, member);
		}

		public virtual bool ContainsKey(Int32 id)
		{
			EmployeesByIdKey _key_ = new EmployeesByIdKey(id);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Employee))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(EmployeesByIdKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(EmployeesByIdMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("EmployeesById", "RootSchema.JadeProject", ClassNamespace="JadeProject")]
	public abstract partial class EmployeesById<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : Employee
	{

		private static EmployeesByIdMetadata _metaModel;

		partial void Initialize();


		static EmployeesById()
		{
			_metaModel = MetadataCache<EmployeesByIdMetadata>.GetData(null);
		}

		protected EmployeesById(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class EmployeesByIdMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata IdKey;

		private EmployeesByIdMetadata()
		{
		}

		public EmployeesByIdMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(EmployeesById), "EmployeesById", "RootSchema.JadeProject", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.IdKey = metaClass.CheckMemberKey(typeof(EmployeesById), typeof(Employee), "id", typeof(Int32), JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
