//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 16.0.02
//      Generation date : niedziela, 6 maja 2018
//      Generated by    : DominikaRaczak
//      JADE Schema     : JadeProject
//      Exposure Name   : JadeProject
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace JadeProject
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Position))]
	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(EmployeeMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("Employee", "RootSchema.JadeProject", ClassNamespace="JadeProject")]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.Class, "Employee", typeof(Person))]
	public partial class Employee : Person
	{
		private static EmployeeMetadata _metaModel;
		partial void _initialize();
		static Employee()
		{
			_metaModel = MetadataCache<EmployeeMetadata>.GetData(null);
		}
		public Employee() :
			this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}
		public Employee(JadeSoftware.Joob.ClassPersistence lifetime) :
			base(lifetime, typeof(Employee), _metaModel.metaClass)
		{
			this._initialize();
		}
		protected Employee(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
			base(lifetime, type, metaClass)
		{
			this._initialize();
		}
	
#region Jade Properties

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("position", typeof(Position), DatabaseTypeName="Position")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public Position Position
		{
			get
			{
				return this.GetPropertyReference<Position>(_metaModel.metaClass, _metaModel.position);
			}
			set
			{
				this.SetPropertyReference(_metaModel.metaClass, _metaModel.position, value, false);
			}
		}
	#endregion
	
#region Jade Methods

		[JadeSoftware.Joob.Client.JoobMethodAttribute("canHaveDiscount")]
		public new Boolean CanHaveDiscount()
		{
			using (JadeParam retnParam = new JadeParamBoolean(Usage.Output))
			{
				this.SendMessage(_metaModel.canHaveDiscount, retnParam);
				return (retnParam as JadeParamBoolean).Value;
			}

		}

		[JadeSoftware.Joob.Client.JoobMethodAttribute("setOnCreate")]
		public void SetOnCreate(String pName, String pSurname, Int32 pAge, Int32 pDiscount, Position pPosition)
		{
			using (JadeParam jadeParam1 = new JadeParamString(pName),
							jadeParam2 = new JadeParamString(pSurname),
							jadeParam3 = new JadeParamInteger(pAge),
							jadeParam4 = new JadeParamInteger(pDiscount),
							jadeParam5 = new JadeParamObject(pPosition))
			{
				this.SendMessage(_metaModel.setOnCreate, null, jadeParam1, jadeParam2, jadeParam3, jadeParam4, jadeParam5);
				return;
			}

		}
	#endregion
	}

	public partial class EmployeeMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;
		internal JadeSoftware.Joob.MethodMetadata canHaveDiscount;
		internal JadeSoftware.Joob.PropertyMetadata position;
		internal JadeSoftware.Joob.MethodMetadata setOnCreate;

		private EmployeeMetadata()
		{
		}
		partial void InitializeDynamicProperties(JadeSoftware.Joob.Client.IJoobConnection connection);

		public EmployeeMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(Employee), "Employee", "RootSchema.JadeProject");
			this.InitializeProperties(connection);
			this.InitializeDynamicProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.IJoobConnection connection)
		{
			canHaveDiscount = metaClass.CheckMethod(metaClass,"canHaveDiscount");
			position = metaClass.CheckProperty("position", typeof(Position));
			setOnCreate = metaClass.CheckMethod(metaClass,"setOnCreate");
		}
	}
}
