//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 16.0.02
//      Generation date : niedziela, 6 maja 2018
//      Generated by    : DominikaRaczak
//      JADE Schema     : JadeProject
//      Exposure Name   : JadeProject
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace JadeProject
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(ItemsByName))]
	public partial class ItemsByNameKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _name = MetadataCache<ItemsByNameMetadata>.GetData(null).NameKey;

		public ItemsByNameKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_name})
		{
		}

		public ItemsByNameKey(String name) :
				this()
		{
			this.Name = name;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("name", 0, typeof(String), Length = 30, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public String Name
		{
			get
			{
				return ((String)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Item))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemsByNameKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(ItemsByNameMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("ItemsByName", "RootSchema.JadeProject", ClassNamespace = "JadeProject", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "ItemsByName", typeof(MemberKeyDictionary<ItemsByNameKey, Item>), MembershipType=typeof(Item), Keys="name")]
	public partial class ItemsByName : MemberKeyDictionary<ItemsByNameKey, Item>
	{

		private static ItemsByNameMetadata _metaModel;

		partial void Initialize();


		static ItemsByName()
		{
			_metaModel = MetadataCache<ItemsByNameMetadata>.GetData(null);
		}

		private ItemsByName() : 
				this(JadeSoftware.Joob.ClassPersistence.Transient)
		{
		}

		public ItemsByName(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(ItemsByName), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected ItemsByName(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual Item this[String name]
		{
			get
			{
				ItemsByNameKey _key_ = new ItemsByNameKey(name);
				 return base[_key_];
			}
			set
			{
				ItemsByNameKey _key_ = new ItemsByNameKey(name);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(String name, out Item value)
		{
			ItemsByNameKey _key_ = new ItemsByNameKey(name);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(String name, JadeSoftware.Joob.SearchStrategy strategy, out Item value)
		{
			ItemsByNameKey _key_ = new ItemsByNameKey(name);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<ItemsByNameKey, Item> StartingAtKey(String name)
		{
			ItemsByNameKey _key_ = new ItemsByNameKey(name);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<ItemsByNameKey, Item> StartingAtKey(String name, JadeSoftware.Joob.SearchStrategy strategy)
		{
			ItemsByNameKey _key_ = new ItemsByNameKey(name);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void Remove(String name)
		{
			ItemsByNameKey _key_ = new ItemsByNameKey(name);
			base.Remove(_key_);
		}

		public virtual void Remove(String name, Item member)
		{
			ItemsByNameKey _key_ = new ItemsByNameKey(name);
			base.Remove(_key_, member);
		}

		public virtual bool ContainsKey(String name)
		{
			ItemsByNameKey _key_ = new ItemsByNameKey(name);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Item))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ItemsByNameKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(ItemsByNameMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("ItemsByName", "RootSchema.JadeProject", ClassNamespace="JadeProject")]
	public abstract partial class ItemsByName<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : Item
	{

		private static ItemsByNameMetadata _metaModel;

		partial void Initialize();


		static ItemsByName()
		{
			_metaModel = MetadataCache<ItemsByNameMetadata>.GetData(null);
		}

		protected ItemsByName(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class ItemsByNameMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata NameKey;

		private ItemsByNameMetadata()
		{
		}

		public ItemsByNameMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(ItemsByName), "ItemsByName", "RootSchema.JadeProject", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.NameKey = metaClass.CheckMemberKey(typeof(ItemsByName), typeof(Item), "name", typeof(String), 30, JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
