//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 16.0.02
//      Generation date : niedziela, 6 maja 2018
//      Generated by    : DominikaRaczak
//      JADE Schema     : JadeProject
//      Exposure Name   : JadeProject
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace JadeProject
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Item))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(ItemsMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("Items", "RootSchema.JadeProject", ClassNamespace="JadeProject")]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "Items", typeof(ObjectArray<Item>), MembershipType=typeof(Item))]
	public partial class Items : ObjectArray<Item>
	{

		private static ItemsMetadata _metaModel;

		partial void Initialize();


		static Items()
		{
			_metaModel = MetadataCache<ItemsMetadata>.GetData(null);
		}

		private Items() : 
				this(JadeSoftware.Joob.ClassPersistence.Transient)
		{
		}

		public Items(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(Items), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected Items(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public class ItemsMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		private ItemsMetadata()
		{
		}

		public ItemsMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(Items), "Items", "RootSchema.JadeProject", JadeSoftware.Joob.DuplicationOption.NotAllowed);
		}
	}
}
