//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 16.0.02
//      Generation date : niedziela, 6 maja 2018
//      Generated by    : DominikaRaczak
//      JADE Schema     : JadeProject
//      Exposure Name   : JadeProject
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace JadeProject
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;

	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(ItemMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("Item", "RootSchema.JadeProject", ClassNamespace="JadeProject")]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.Class, "Item", typeof(JoobObject))]
	public partial class Item : JoobObject
	{
		private static ItemMetadata _metaModel;
		partial void _initialize();
		static Item()
		{
			_metaModel = MetadataCache<ItemMetadata>.GetData(null);
		}
		public Item() :
			this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}
		public Item(JadeSoftware.Joob.ClassPersistence lifetime) :
			base(lifetime, typeof(Item), _metaModel.metaClass)
		{
			this._initialize();
		}
		protected Item(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
			base(lifetime, type, metaClass)
		{
			this._initialize();
		}
	
#region Jade Properties

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("id", typeof(Int32), DatabaseTypeName="Integer")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public Int32 Id
		{
			get
			{
				return this.GetPropertyInt32(_metaModel.metaClass, _metaModel.id);
			}
			set
			{
				this.SetPropertyInt32(_metaModel.metaClass, _metaModel.id, value);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("name", typeof(String), Length=30, DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String Name
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.name);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.name, value);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("price", typeof(Decimal), Precision=12, Scale=2, DatabaseTypeName="Decimal")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public Decimal Price
		{
			get
			{
				return this.GetPropertyDecimal(_metaModel.metaClass, _metaModel.price);
			}
			set
			{
				this.SetPropertyDecimal(_metaModel.metaClass, _metaModel.price, value);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("weight", typeof(Decimal), Precision=12, Scale=2, DatabaseTypeName="Decimal")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public Decimal Weight
		{
			get
			{
				return this.GetPropertyDecimal(_metaModel.metaClass, _metaModel.weight);
			}
			set
			{
				this.SetPropertyDecimal(_metaModel.metaClass, _metaModel.weight, value);
			}
		}
	#endregion
	
#region Jade Methods

		[JadeSoftware.Joob.Client.JoobMethodAttribute("setOnCreate")]
		public void SetOnCreate(String pName, Decimal pPrice, Decimal pWeight)
		{
			using (JadeParam jadeParam1 = new JadeParamString(pName),
							jadeParam2 = new JadeParamDecimal(pPrice),
							jadeParam3 = new JadeParamDecimal(pWeight))
			{
				this.SendMessage(_metaModel.setOnCreate, null, jadeParam1, jadeParam2, jadeParam3);
				return;
			}

		}
	#endregion
	}

	public partial class ItemMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;
		internal JadeSoftware.Joob.PropertyMetadata id;
		internal JadeSoftware.Joob.PropertyMetadata name;
		internal JadeSoftware.Joob.PropertyMetadata price;
		internal JadeSoftware.Joob.MethodMetadata setOnCreate;
		internal JadeSoftware.Joob.PropertyMetadata weight;

		private ItemMetadata()
		{
		}
		partial void InitializeDynamicProperties(JadeSoftware.Joob.Client.IJoobConnection connection);

		public ItemMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(Item), "Item", "RootSchema.JadeProject");
			this.InitializeProperties(connection);
			this.InitializeDynamicProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.IJoobConnection connection)
		{
			id = metaClass.CheckProperty("id", typeof(Int32));
			name = metaClass.CheckProperty("name", typeof(String), 30);
			price = metaClass.CheckProperty("price", typeof(Decimal), 12, 2);
			setOnCreate = metaClass.CheckMethod(metaClass,"setOnCreate");
			weight = metaClass.CheckProperty("weight", typeof(Decimal), 12, 2);
		}
	}
}
