//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 16.0.02
//      Generation date : niedziela, 6 maja 2018
//      Generated by    : DominikaRaczak
//      JADE Schema     : JadeProject
//      Exposure Name   : JadeProject
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace JadeProject
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Shop))]
	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(JadeProjectMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("JadeProject", "RootSchema.JadeProject", ClassNamespace="JadeProject")]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.Class, "JadeProject", typeof(JoobObject))]
	public partial class JadeProject : JoobObject
	{
		private static JadeProjectMetadata _metaModel;
		partial void _initialize();
		static JadeProject()
		{
			_metaModel = MetadataCache<JadeProjectMetadata>.GetData(null);
		}
		public JadeProject() :
			this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}
		public JadeProject(JadeSoftware.Joob.ClassPersistence lifetime) :
			base(lifetime, typeof(JadeProject), _metaModel.metaClass)
		{
			this._initialize();
		}
		protected JadeProject(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
			base(lifetime, type, metaClass)
		{
			this._initialize();
		}
	
#region Jade Properties

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("myShop", typeof(Shop), DatabaseTypeName="Shop")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public Shop MyShop
		{
			get
			{
				return this.GetPropertyReference<Shop>(_metaModel.metaClass, _metaModel.myShop);
			}
			set
			{
				this.SetPropertyReference(_metaModel.metaClass, _metaModel.myShop, value, false);
			}
		}
	#endregion
	
#region Jade Methods

		[JadeSoftware.Joob.Client.JoobMethodAttribute("setRootObject")]
		public void SetRootObject()
		{
			{
				this.SendMessage(_metaModel.setRootObject, null);
				return;
			}

		}
	#endregion
	}

	public partial class JadeProjectMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;
		internal JadeSoftware.Joob.PropertyMetadata myShop;
		internal JadeSoftware.Joob.MethodMetadata setRootObject;

		private JadeProjectMetadata()
		{
		}
		partial void InitializeDynamicProperties(JadeSoftware.Joob.Client.IJoobConnection connection);

		public JadeProjectMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(JadeProject), "JadeProject", "RootSchema.JadeProject");
			this.InitializeProperties(connection);
			this.InitializeDynamicProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.IJoobConnection connection)
		{
			myShop = metaClass.CheckProperty("myShop", typeof(Shop));
			setRootObject = metaClass.CheckMethod(metaClass,"setRootObject");
		}
	}
}
