//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 16.0.02
//      Generation date : niedziela, 6 maja 2018
//      Generated by    : DominikaRaczak
//      JADE Schema     : JadeProject
//      Exposure Name   : JadeProject
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace JadeProject
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Cart))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Customer))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Employee))]
	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(PersonMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("Person", "RootSchema.JadeProject", ClassNamespace="JadeProject")]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.Class, "Person", typeof(JoobObject))]
	public partial class Person : JoobObject
	{
		private static PersonMetadata _metaModel;
		partial void _initialize();
		static Person()
		{
			_metaModel = MetadataCache<PersonMetadata>.GetData(null);
		}
		public Person() :
			this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}
		public Person(JadeSoftware.Joob.ClassPersistence lifetime) :
			base(lifetime, typeof(Person), _metaModel.metaClass)
		{
			this._initialize();
		}
		protected Person(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
			base(lifetime, type, metaClass)
		{
			this._initialize();
		}
	
#region Jade Properties

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("age", typeof(Int32), DatabaseTypeName="Integer")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public Int32 Age
		{
			get
			{
				return this.GetPropertyInt32(_metaModel.metaClass, _metaModel.age);
			}
			set
			{
				this.SetPropertyInt32(_metaModel.metaClass, _metaModel.age, value);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("cart", typeof(Cart), DatabaseTypeName="Cart")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public Cart Cart
		{
			get
			{
				return this.GetPropertyReference<Cart>(_metaModel.metaClass, _metaModel.cart);
			}
			set
			{
				this.SetPropertyReference(_metaModel.metaClass, _metaModel.cart, value, false);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("discount", typeof(Int32), DatabaseTypeName="Integer")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public Int32 Discount
		{
			get
			{
				return this.GetPropertyInt32(_metaModel.metaClass, _metaModel.discount);
			}
			set
			{
				this.SetPropertyInt32(_metaModel.metaClass, _metaModel.discount, value);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("id", typeof(Int32), DatabaseTypeName="Integer")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public Int32 Id
		{
			get
			{
				return this.GetPropertyInt32(_metaModel.metaClass, _metaModel.id);
			}
			set
			{
				this.SetPropertyInt32(_metaModel.metaClass, _metaModel.id, value);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("name", typeof(String), Length=30, DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String Name
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.name);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.name, value);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("surname", typeof(String), Length=30, DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String Surname
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.surname);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.surname, value);
			}
		}
	#endregion
	
#region Jade Methods

		[JadeSoftware.Joob.Client.JoobMethodAttribute("canHaveDiscount")]
		public Boolean CanHaveDiscount()
		{
			using (JadeParam retnParam = new JadeParamBoolean(Usage.Output))
			{
				this.SendMessage(_metaModel.canHaveDiscount, retnParam);
				return (retnParam as JadeParamBoolean).Value;
			}

		}
	#endregion
	}

	public partial class PersonMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;
		internal JadeSoftware.Joob.PropertyMetadata age;
		internal JadeSoftware.Joob.MethodMetadata canHaveDiscount;
		internal JadeSoftware.Joob.PropertyMetadata cart;
		internal JadeSoftware.Joob.PropertyMetadata discount;
		internal JadeSoftware.Joob.PropertyMetadata id;
		internal JadeSoftware.Joob.PropertyMetadata name;
		internal JadeSoftware.Joob.PropertyMetadata surname;

		private PersonMetadata()
		{
		}
		partial void InitializeDynamicProperties(JadeSoftware.Joob.Client.IJoobConnection connection);

		public PersonMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(Person), "Person", "RootSchema.JadeProject");
			this.InitializeProperties(connection);
			this.InitializeDynamicProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.IJoobConnection connection)
		{
			age = metaClass.CheckProperty("age", typeof(Int32));
			canHaveDiscount = metaClass.CheckMethod(metaClass,"canHaveDiscount");
			cart = metaClass.CheckProperty("cart", typeof(Cart));
			discount = metaClass.CheckProperty("discount", typeof(Int32));
			id = metaClass.CheckProperty("id", typeof(Int32));
			name = metaClass.CheckProperty("name", typeof(String), 30);
			surname = metaClass.CheckProperty("surname", typeof(String), 30);
		}
	}
}
