//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 16.0.02
//      Generation date : niedziela, 6 maja 2018
//      Generated by    : DominikaRaczak
//      JADE Schema     : JadeProject
//      Exposure Name   : JadeProject
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace JadeProject
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(Positions))]
	public partial class PositionsKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _title = MetadataCache<PositionsMetadata>.GetData(null).TitleKey;

		public PositionsKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_title})
		{
		}

		public PositionsKey(String title) :
				this()
		{
			this.Title = title;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("title", 0, typeof(String), Length = 30, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public String Title
		{
			get
			{
				return ((String)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Position))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(PositionsKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(PositionsMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("Positions", "RootSchema.JadeProject", ClassNamespace = "JadeProject", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "Positions", typeof(MemberKeyDictionary<PositionsKey, Position>), MembershipType=typeof(Position), Keys="title")]
	public partial class Positions : MemberKeyDictionary<PositionsKey, Position>
	{

		private static PositionsMetadata _metaModel;

		partial void Initialize();


		static Positions()
		{
			_metaModel = MetadataCache<PositionsMetadata>.GetData(null);
		}

		private Positions() : 
				this(JadeSoftware.Joob.ClassPersistence.Transient)
		{
		}

		public Positions(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(Positions), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected Positions(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual Position this[String title]
		{
			get
			{
				PositionsKey _key_ = new PositionsKey(title);
				 return base[_key_];
			}
			set
			{
				PositionsKey _key_ = new PositionsKey(title);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(String title, out Position value)
		{
			PositionsKey _key_ = new PositionsKey(title);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(String title, JadeSoftware.Joob.SearchStrategy strategy, out Position value)
		{
			PositionsKey _key_ = new PositionsKey(title);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<PositionsKey, Position> StartingAtKey(String title)
		{
			PositionsKey _key_ = new PositionsKey(title);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<PositionsKey, Position> StartingAtKey(String title, JadeSoftware.Joob.SearchStrategy strategy)
		{
			PositionsKey _key_ = new PositionsKey(title);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void Remove(String title)
		{
			PositionsKey _key_ = new PositionsKey(title);
			base.Remove(_key_);
		}

		public virtual void Remove(String title, Position member)
		{
			PositionsKey _key_ = new PositionsKey(title);
			base.Remove(_key_, member);
		}

		public virtual bool ContainsKey(String title)
		{
			PositionsKey _key_ = new PositionsKey(title);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Position))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(PositionsKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(PositionsMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("Positions", "RootSchema.JadeProject", ClassNamespace="JadeProject")]
	public abstract partial class Positions<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : Position
	{

		private static PositionsMetadata _metaModel;

		partial void Initialize();


		static Positions()
		{
			_metaModel = MetadataCache<PositionsMetadata>.GetData(null);
		}

		protected Positions(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class PositionsMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata TitleKey;

		private PositionsMetadata()
		{
		}

		public PositionsMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(Positions), "Positions", "RootSchema.JadeProject", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.TitleKey = metaClass.CheckMemberKey(typeof(Positions), typeof(Position), "title", typeof(String), 30, JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
