//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 16.0.02
//      Generation date : niedziela, 6 maja 2018
//      Generated by    : DominikaRaczak
//      JADE Schema     : JadeProject
//      Exposure Name   : JadeProject
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace JadeProject
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;

	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(PositionMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("Position", "RootSchema.JadeProject", ClassNamespace="JadeProject")]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.Class, "Position", typeof(JoobObject))]
	public partial class Position : JoobObject
	{
		private static PositionMetadata _metaModel;
		partial void _initialize();
		static Position()
		{
			_metaModel = MetadataCache<PositionMetadata>.GetData(null);
		}
		public Position() :
			this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}
		public Position(JadeSoftware.Joob.ClassPersistence lifetime) :
			base(lifetime, typeof(Position), _metaModel.metaClass)
		{
			this._initialize();
		}
		protected Position(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
			base(lifetime, type, metaClass)
		{
			this._initialize();
		}
	
#region Jade Properties

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("salary", typeof(Int32), DatabaseTypeName="Integer")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public Int32 Salary
		{
			get
			{
				return this.GetPropertyInt32(_metaModel.metaClass, _metaModel.salary);
			}
			set
			{
				this.SetPropertyInt32(_metaModel.metaClass, _metaModel.salary, value);
			}
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("title", typeof(String), Length=30, DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String Title
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.title);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.title, value);
			}
		}
	#endregion
	
#region Jade Methods

		[JadeSoftware.Joob.Client.JoobMethodAttribute("setOnCreate")]
		public void SetOnCreate(String pTitle, Int32 pSalary)
		{
			using (JadeParam jadeParam1 = new JadeParamString(pTitle),
							jadeParam2 = new JadeParamInteger(pSalary))
			{
				this.SendMessage(_metaModel.setOnCreate, null, jadeParam1, jadeParam2);
				return;
			}

		}
	#endregion
	}

	public partial class PositionMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;
		internal JadeSoftware.Joob.PropertyMetadata salary;
		internal JadeSoftware.Joob.MethodMetadata setOnCreate;
		internal JadeSoftware.Joob.PropertyMetadata title;

		private PositionMetadata()
		{
		}
		partial void InitializeDynamicProperties(JadeSoftware.Joob.Client.IJoobConnection connection);

		public PositionMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(Position), "Position", "RootSchema.JadeProject");
			this.InitializeProperties(connection);
			this.InitializeDynamicProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.IJoobConnection connection)
		{
			salary = metaClass.CheckProperty("salary", typeof(Int32));
			setOnCreate = metaClass.CheckMethod(metaClass,"setOnCreate");
			title = metaClass.CheckProperty("title", typeof(String), 30);
		}
	}
}
